# Generated by Django 4.2.4 on 2023-10-03 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('duration', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('access_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edSystemApp.accesslevels')),
            ],
        ),
        migrations.CreateModel(
            name='ViewStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewingDuration', models.PositiveSmallIntegerField()),
                ('viewLesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edSystemApp.lesson')),
                ('viewingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edSystemApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=120)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edSystemApp.lesson')),
                ('user_access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edSystemApp.accesslevels')),
            ],
        ),
    ]
